version: '3.0'
services:
  messagesNosql:
    image: mongo:4.2.12-bionic
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_DATABASE=messages
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  videogamesNosql:
    image: mongo:4.2.12-bionic
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=videogames
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181
  kafkaBroker:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper